In [143]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [144]:
df = pd.read_csv("/Data.csv")

In [145]:
df.head(2)

,Age,Gender,Education,Experience,Department,City,Job_Level,Performance_Score,Years_at_Company,Salary
0,22,Male,Bachelors,1.0,IT,Hyderabad,Junior,3.0,1,320000
1,25,Female,Masters,3.0,HR,Bangalore,Junior,4.0,2,420000

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                30 non-null     int64
 1   Gender             30 non-null     object
 2   Education          30 non-null     object
 3   Experience         29 non-null     float64
 4   Department         30 non-null     object
 5   City               30 non-null     object
 6   Job_Level          30 non-null     object
 7   Performance_Score  29 non-null     float64
 8   Years_at_Company   30 non-null     int64
 9   Salary             30 non-null     int64
dtypes: float64(2), int64(3), object(5)
memory usage: 2.5+ KB

In [ ]:
#select only numeric values cloumns
numerical_values = df.select_dtypes(include=['int64', 'float64'])

In [ ]:
#selects only categorical data columns
categorical_values = df.select_dtypes(exclude=['int64', 'float64'])

In [149]:
df['City'].unique()

array(['Hyderabad', 'Bangalore', 'Chennai', 'Mumbai'], dtype=object)

In [150]:
df['Education'].unique() #bachelors < masters < phd
#so we have ordinal data and we should do lable encoding.

array(['Bachelors', 'Masters', 'PhD'], dtype=object)

In [151]:
x = df['Experience'].dropna()

In [152]:
df.head()

,Age,Gender,Education,Experience,Department,City,Job_Level,Performance_Score,Years_at_Company,Salary
0,22,Male,Bachelors,1.0,IT,Hyderabad,Junior,3.0,1,320000
1,25,Female,Masters,3.0,HR,Bangalore,Junior,4.0,2,420000
2,28,Male,Bachelors,5.0,IT,Hyderabad,Mid,3.0,4,550000
3,30,Female,Masters,7.0,Finance,Chennai,Mid,4.0,6,680000
4,35,Male,PhD,10.0,IT,Bangalore,Senior,5.0,9,950000

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                30 non-null     int64
 1   Gender             30 non-null     object
 2   Education          30 non-null     object
 3   Experience         29 non-null     float64
 4   Department         30 non-null     object
 5   City               30 non-null     object
 6   Job_Level          30 non-null     object
 7   Performance_Score  29 non-null     float64
 8   Years_at_Company   30 non-null     int64
 9   Salary             30 non-null     int64
dtypes: float64(2), int64(3), object(5)
memory usage: 2.5+ KB

In [154]:
df = df.dropna(subset=['Experience','Performance_Score'])

In [155]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 0 to 29
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                28 non-null     int64
 1   Gender             28 non-null     object
 2   Education          28 non-null     object
 3   Experience         28 non-null     float64
 4   Department         28 non-null     object
 5   City               28 non-null     object
 6   Job_Level          28 non-null     object
 7   Performance_Score  28 non-null     float64
 8   Years_at_Company   28 non-null     int64
 9   Salary             28 non-null     int64
dtypes: float64(2), int64(3), object(5)
memory usage: 2.4+ KB

In [156]:
df.head()

,Age,Gender,Education,Experience,Department,City,Job_Level,Performance_Score,Years_at_Company,Salary
0,22,Male,Bachelors,1.0,IT,Hyderabad,Junior,3.0,1,320000
1,25,Female,Masters,3.0,HR,Bangalore,Junior,4.0,2,420000
2,28,Male,Bachelors,5.0,IT,Hyderabad,Mid,3.0,4,550000
3,30,Female,Masters,7.0,Finance,Chennai,Mid,4.0,6,680000
4,35,Male,PhD,10.0,IT,Bangalore,Senior,5.0,9,950000

In [157]:
numerical_values
numerical_values.info()
nv = numerical_values.fillna(numerical_values.mean())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                30 non-null     int64
 1   Experience         29 non-null     float64
 2   Performance_Score  29 non-null     float64
 3   Years_at_Company   30 non-null     int64
 4   Salary             30 non-null     int64
dtypes: float64(2), int64(3)
memory usage: 1.3 KB

In [158]:
cv = categorical_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      30 non-null     object
 1   Education   30 non-null     object
 2   Department  30 non-null     object
 3   City        30 non-null     object
 4   Job_Level   30 non-null     object
dtypes: object(5)
memory usage: 1.3+ KB

In [159]:
nv.isnull().sum()

Age                  0
Experience           0
Performance_Score    0
Years_at_Company     0
Salary               0
dtype: int64

In [160]:
sorted_numeric_data = nv.astype(int)

In [161]:
sorted_numeric_data

    Age  Experience  Performance_Score  Years_at_Company   Salary
0    22           1                  3                 1   320000
1    25           3                  4                 2   420000
2    28           5                  3                 4   550000
3    30           7                  4                 6   680000
4    35          10                  5                 9   950000
5    26           3                  3                 2   400000
6    40          15                  4                12  1200000
7    29           6                  3                 5   600000
8    32           8                  4                 7   720000
9    45          20                  5                15  1500000
10   24           2                  2                 1   350000
11   27           4                  4                 3   500000
12   31           7                  3                 6   650000
13   38          12                  5                10  1050000
14   42          18                  4                14  1350000
15   23           1                  3                 1   310000
16   36          11                  4                 9  1000000
17   33           8                  3                 7   700000
18   29           8                  4                 5   620000
19   41          17                  5                13  1400000
20   27           4                  3                 3   480000
21   34           9                  4                 8   780000
22   39          14                  5                11  1100000
23   25           2                  3                 2   380000
24   31           6                  3                 5   640000
25   28           5                  4                 4   570000
26   37          10                  4                 9   900000
27   44          22                  5                18  2000000
28   30           7                  3                 6   590000
29   26           3                  4                 2   450000

In [162]:
sorted_categoric_data = categorical_values

In [163]:
sorted_categoric_data.isnull().sum()

Gender        0
Education     0
Department    0
City          0
Job_Level     0
dtype: int64

In [164]:
df.isnull().sum()

Age                  0
Gender               0
Education            0
Experience           0
Department           0
City                 0
Job_Level            0
Performance_Score    0
Years_at_Company     0
Salary               0
dtype: int64

In [165]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 0 to 29
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                28 non-null     int64
 1   Gender             28 non-null     object
 2   Education          28 non-null     object
 3   Experience         28 non-null     float64
 4   Department         28 non-null     object
 5   City               28 non-null     object
 6   Job_Level          28 non-null     object
 7   Performance_Score  28 non-null     float64
 8   Years_at_Company   28 non-null     int64
 9   Salary             28 non-null     int64
dtypes: float64(2), int64(3), object(5)
memory usage: 2.4+ KB

## LABLE ENCODER

In [ ]:
#lable encoder is used to encode the values into unit values.
#This is used only for ordinal data.
#ordinal data means the values are related to each other(having relation).

le = LabelEncoder()

In [167]:
scd = ['Gender','Education','Job_Level','Department','City']

In [168]:
for col in scd:
  df[col] = le.fit_transform(df[col])

In [169]:
df.head()

,Age,Gender,Education,Experience,Department,City,Job_Level,Performance_Score,Years_at_Company,Salary
0,22,1,0,1.0,2,2,0,3.0,1,320000
1,25,0,1,3.0,1,0,0,4.0,2,420000
2,28,1,0,5.0,2,2,1,3.0,4,550000
3,30,0,1,7.0,0,1,1,4.0,6,680000
4,35,1,2,10.0,2,0,2,5.0,9,950000

In [170]:
df.isnull().sum()

Age                  0
Gender               0
Education            0
Experience           0
Department           0
City                 0
Job_Level            0
Performance_Score    0
Years_at_Company     0
Salary               0
dtype: int64

In [171]:
df

,Age,Gender,Education,Experience,Department,City,Job_Level,Performance_Score,Years_at_Company,Salary
0,22,1,0,1.0,2,2,0,3.0,1,320000
1,25,0,1,3.0,1,0,0,4.0,2,420000
2,28,1,0,5.0,2,2,1,3.0,4,550000
3,30,0,1,7.0,0,1,1,4.0,6,680000
4,35,1,2,10.0,2,0,2,5.0,9,950000
5,26,0,0,3.0,3,2,0,3.0,2,400000
6,40,1,1,15.0,0,3,2,4.0,12,1200000
7,29,0,0,6.0,2,1,1,3.0,5,600000
8,32,1,1,8.0,1,0,1,4.0,7,720000
9,45,0,2,20.0,0,3,2,5.0,15,1500000
10,24,1,0,2.0,3,2,0,2.0,1,350000
11,27,0,1,4.0,2,0,0,4.0,3,500000
12,31,1,0,7.0,2,1,1,3.0,6,650000
13,38,0,1,12.0,1,3,2,5.0,10,1050000
14,42,1,2,18.0,2,0,2,4.0,14,1350000
15,23,0,0,1.0,3,2,0,3.0,1,310000
16,36,1,1,11.0,0,1,2,4.0,9,1000000
17,33,0,0,8.0,2,0,1,3.0,7,700000
19,41,0,2,17.0,0,3,2,5.0,13,1400000
20,27,1,0,4.0,2,1,0,3.0,3,480000
21,34,0,1,9.0,3,0,1,4.0,8,780000
22,39,1,2,14.0,2,3,2,5.0,11,1100000
23,25,0,0,2.0,1,2,0,3.0,2,380000
25,28,0,0,5.0,2,0,1,4.0,4,570000
26,37,1,1,10.0,3,3,2,4.0,9,900000
27,44,0,2,22.0,0,1,2,5.0,18,2000000
28,30,1,0,7.0,1,2,1,3.0,6,590000
29,26,0,1,3.0,2,0,0,4.0,2,450000