In [79]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix

In [80]:
df = pd.read_csv("test.csv")

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25976 entries, 0 to 25975
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Unnamed: 0                         25976 non-null  int64
 1   id                                 25976 non-null  int64
 2   Gender                             25976 non-null  object
 3   Customer Type                      25976 non-null  object
 4   Age                                25976 non-null  int64
 5   Type of Travel                     25976 non-null  object
 6   Class                              25976 non-null  object
 7   Flight Distance                    25976 non-null  int64
 8   Inflight wifi service              25976 non-null  int64
 9   Departure/Arrival time convenient  25976 non-null  int64
 10  Ease of Online booking             25976 non-null  int64
 11  Gate location                      25976 non-null  int64
 12  Food and drink                     25976 non-null  int64
 13  Online boarding                    25976 non-null  int64
 14  Seat comfort                       25976 non-null  int64
 15  Inflight entertainment             25976 non-null  int64
 16  On-board service                   25976 non-null  int64
 17  Leg room service                   25976 non-null  int64
 18  Baggage handling                   25976 non-null  int64
 19  Checkin service                    25976 non-null  int64
 20  Inflight service                   25976 non-null  int64
 21  Cleanliness                        25976 non-null  int64
 22  Departure Delay in Minutes         25976 non-null  int64
 23  Arrival Delay in Minutes           25893 non-null  float64
 24  satisfaction                       25976 non-null  object
dtypes: float64(1), int64(19), object(5)
memory usage: 5.0+ MB

In [82]:
df.isnull().sum()

Unnamed: 0                            0
id                                    0
Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             83
satisfaction                          0
dtype: int64

In [83]:
df.head(2)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44.0,satisfied
1,1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,satisfied

In [84]:
df = df.drop(columns=['id','Gender','Gate location'],axis=1)

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25976 entries, 0 to 25975
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Unnamed: 0                         25976 non-null  int64
 1   Customer Type                      25976 non-null  object
 2   Age                                25976 non-null  int64
 3   Type of Travel                     25976 non-null  object
 4   Class                              25976 non-null  object
 5   Flight Distance                    25976 non-null  int64
 6   Inflight wifi service              25976 non-null  int64
 7   Departure/Arrival time convenient  25976 non-null  int64
 8   Ease of Online booking             25976 non-null  int64
 9   Food and drink                     25976 non-null  int64
 10  Online boarding                    25976 non-null  int64
 11  Seat comfort                       25976 non-null  int64
 12  Inflight entertainment             25976 non-null  int64
 13  On-board service                   25976 non-null  int64
 14  Leg room service                   25976 non-null  int64
 15  Baggage handling                   25976 non-null  int64
 16  Checkin service                    25976 non-null  int64
 17  Inflight service                   25976 non-null  int64
 18  Cleanliness                        25976 non-null  int64
 19  Departure Delay in Minutes         25976 non-null  int64
 20  Arrival Delay in Minutes           25893 non-null  float64
 21  satisfaction                       25976 non-null  object
dtypes: float64(1), int64(17), object(4)
memory usage: 4.4+ MB

In [86]:
df['Arrival Delay in Minutes'] #those are not null values they are 0.

0        44.0
1         0.0
2         0.0
3         6.0
4        20.0
         ...
25971     0.0
25972     0.0
25973     0.0
25974     0.0
25975     0.0
Name: Arrival Delay in Minutes, Length: 25976, dtype: float64

In [87]:
df= df.replace(to_replace=['neutral or dissatisfied','satisfied'],value=[0,1])

/tmp/ipykernel_12780/75600721.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df= df.replace(to_replace=['neutral or dissatisfied','satisfied'],value=[0,1])

In [88]:
df.head(5)

,Unnamed: 0,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Food and drink,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,Loyal Customer,52,Business travel,Eco,160,5,4,3,3,...,5,5,5,5,2,5,5,50,44.0,1
1,1,Loyal Customer,36,Business travel,Business,2863,1,1,3,5,...,4,4,4,4,3,4,5,0,0.0,1
2,2,disloyal Customer,20,Business travel,Eco,192,2,0,2,2,...,2,4,1,3,2,2,2,0,0.0,0
3,3,Loyal Customer,44,Business travel,Business,3377,0,0,0,3,...,1,1,1,1,3,1,4,0,6.0,1
4,4,Loyal Customer,49,Business travel,Eco,1182,2,3,4,4,...,2,2,2,2,4,2,4,0,20.0,1

In [89]:
df['satisfaction'].astype(int)

0        1
1        1
2        0
3        1
4        1
        ..
25971    0
25972    1
25973    0
25974    1
25975    0
Name: satisfaction, Length: 25976, dtype: int64

In [90]:
X = df.drop(columns=['satisfaction'],axis=1)
y = df['satisfaction']

In [91]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25976 entries, 0 to 25975
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Unnamed: 0                         25976 non-null  int64
 1   Customer Type                      25976 non-null  object
 2   Age                                25976 non-null  int64
 3   Type of Travel                     25976 non-null  object
 4   Class                              25976 non-null  object
 5   Flight Distance                    25976 non-null  int64
 6   Inflight wifi service              25976 non-null  int64
 7   Departure/Arrival time convenient  25976 non-null  int64
 8   Ease of Online booking             25976 non-null  int64
 9   Food and drink                     25976 non-null  int64
 10  Online boarding                    25976 non-null  int64
 11  Seat comfort                       25976 non-null  int64
 12  Inflight entertainment             25976 non-null  int64
 13  On-board service                   25976 non-null  int64
 14  Leg room service                   25976 non-null  int64
 15  Baggage handling                   25976 non-null  int64
 16  Checkin service                    25976 non-null  int64
 17  Inflight service                   25976 non-null  int64
 18  Cleanliness                        25976 non-null  int64
 19  Departure Delay in Minutes         25976 non-null  int64
 20  Arrival Delay in Minutes           25893 non-null  float64
dtypes: float64(1), int64(17), object(3)
memory usage: 4.2+ MB

In [92]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 25976 entries, 0 to 25975
Series name: satisfaction
Non-Null Count  Dtype
--------------  -----
25976 non-null  int64
dtypes: int64(1)
memory usage: 203.1 KB

In [93]:
X.head()

,Unnamed: 0,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Food and drink,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,0,Loyal Customer,52,Business travel,Eco,160,5,4,3,3,...,3,5,5,5,5,2,5,5,50,44.0
1,1,Loyal Customer,36,Business travel,Business,2863,1,1,3,5,...,5,4,4,4,4,3,4,5,0,0.0
2,2,disloyal Customer,20,Business travel,Eco,192,2,0,2,2,...,2,2,4,1,3,2,2,2,0,0.0
3,3,Loyal Customer,44,Business travel,Business,3377,0,0,0,3,...,4,1,1,1,1,3,1,4,0,6.0
4,4,Loyal Customer,49,Business travel,Eco,1182,2,3,4,4,...,2,2,2,2,2,4,2,4,0,20.0

In [94]:
X = pd.get_dummies(
    X,
    columns=['Customer Type','Class','Type of Travel'],
    dtype=int
)

In [95]:
X.head()

,Unnamed: 0,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Food and drink,Online boarding,Seat comfort,Inflight entertainment,...,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Customer Type_Loyal Customer,Customer Type_disloyal Customer,Class_Business,Class_Eco,Class_Eco Plus,Type of Travel_Business travel,Type of Travel_Personal Travel
0,0,52,160,5,4,3,3,4,3,5,...,5,50,44.0,1,0,0,1,0,1,0
1,1,36,2863,1,1,3,5,4,5,4,...,5,0,0.0,1,0,1,0,0,1,0
2,2,20,192,2,0,2,2,2,2,2,...,2,0,0.0,0,1,0,1,0,1,0
3,3,44,3377,0,0,0,3,4,4,1,...,4,0,6.0,1,0,1,0,0,1,0
4,4,49,1182,2,3,4,4,1,2,2,...,4,0,20.0,1,0,0,1,0,1,0

In [96]:
X = X.drop(columns=['Age','Ease of Online booking'])

In [97]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25976 entries, 0 to 25975
Data columns (total 23 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Unnamed: 0                         25976 non-null  int64
 1   Flight Distance                    25976 non-null  int64
 2   Inflight wifi service              25976 non-null  int64
 3   Departure/Arrival time convenient  25976 non-null  int64
 4   Food and drink                     25976 non-null  int64
 5   Online boarding                    25976 non-null  int64
 6   Seat comfort                       25976 non-null  int64
 7   Inflight entertainment             25976 non-null  int64
 8   On-board service                   25976 non-null  int64
 9   Leg room service                   25976 non-null  int64
 10  Baggage handling                   25976 non-null  int64
 11  Checkin service                    25976 non-null  int64
 12  Inflight service                   25976 non-null  int64
 13  Cleanliness                        25976 non-null  int64
 14  Departure Delay in Minutes         25976 non-null  int64
 15  Arrival Delay in Minutes           25893 non-null  float64
 16  Customer Type_Loyal Customer       25976 non-null  int64
 17  Customer Type_disloyal Customer    25976 non-null  int64
 18  Class_Business                     25976 non-null  int64
 19  Class_Eco                          25976 non-null  int64
 20  Class_Eco Plus                     25976 non-null  int64
 21  Type of Travel_Business travel     25976 non-null  int64
 22  Type of Travel_Personal Travel     25976 non-null  int64
dtypes: float64(1), int64(22)
memory usage: 4.6 MB

In [98]:
X['Arrival Delay in Minutes'] = X['Arrival Delay in Minutes'].fillna(X['Arrival Delay in Minutes'].mean())

**LOGISTIC REGRESSION**

In [99]:
lr = LogisticRegression()

In [100]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [101]:
lr.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [102]:
y_pred = lr.predict(X_test)

In [103]:
y_pred

array([0, 1, 0, ..., 1, 1, 1])

In [104]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.76      0.78      2945
           1       0.71      0.77      0.74      2251

    accuracy                           0.76      5196
   macro avg       0.76      0.76      0.76      5196
weighted avg       0.77      0.76      0.76      5196

In [105]:
y_pred_training_data = lr.predict(X_train)

In [106]:
print(classification_report(y_train,y_pred_training_data))

              precision    recall  f1-score   support

           0       0.81      0.76      0.78     11628
           1       0.71      0.77      0.74      9152

    accuracy                           0.76     20780
   macro avg       0.76      0.76      0.76     20780
weighted avg       0.77      0.76      0.76     20780

In [107]:
confusion_matrix(y_test,y_pred)

array([[2239,  706],
       [ 528, 1723]])